accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    # path('login/', views.LoginView.as_view(), name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUpView.as_view(), name='signup'),
    path('profile/', views.CreateProfile.as_view(), name='create_profile'),
    path('dealer/', views.DealerDetails.as_view(), name='dealer_details'),

]

harbacore_home/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'parent_module'

urlpatterns = [
    path('index/', views.Index.as_view(), name="index_page"),
    path('contact-form/', views.contact_form_view, name="contact_form"),
    path('home/', include('home_module.urls', namespace='home_module')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

home_module/urls.py
from django.urls import path

from . import views

app_name = 'home_module'

urlpatterns = [
    path('', views.index, name='index'),
    path('schemes/', views.SchemesListView.as_view(), name="schemes_default_page"),
    path('schemes/<int:scheme_id>', views.SchemesListView.as_view(), name="schemes_detail_page"),
    path('category/', views.ProductListView.as_view(), name="product_default_page"),
    path('category/<int:category_id>', views.ProductListView.as_view(), name="product_list_page"),
    path('test/<int:name>', views.TestListView.as_view(), name="test_list_page"),
    path('cartAdd/', views.AddToCartSessionView.as_view(), name='add_to_cart_session'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('updateCartQuantity/<str:id>/<int:quantity>', views.UpdateCartQuantity.as_view(), name="update_cart_quantity"),
    path('submitOrder/', views.SubmitOrderView.as_view(), name="submit_order")
]

home_module/models.py
from django.db import models
from accounts.models import User

#schemes table for showing SCHEMES
class Schemes(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    image_url = models.TextField(default=None)
    title = models.CharField(max_length=255)
    seo_name = models.CharField(max_length=255, blank=True, null=True)
    terms_and_conditions = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

#Category table
class Category(models.Model):
    category_name = models.TextField()
    seo_name = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.category_name + " - " + self.seo_name + " - " + str(self.id)


# Product variants
class Variants(models.Model):
    variant_name = models.CharField(max_length=255)
    variant_value = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        if self.is_active:
            return self.variant_name + " -  " + self.variant_value
        else:
            return "NOT ACTIVE " + self.variant_name


class Products(models.Model):
    product_category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    mapped_variant = models.ManyToManyField(Variants, blank=True)
    product_name  = models.TextField()
    product_seo_name = models.TextField(null=True)
    product_mrp = models.IntegerField(null=True)
    product_discount = models.FloatField(default=0)
    product_quantity = models.IntegerField(default=0)
    product_description = models.TextField(default=None)
    product_features = models.TextField(default=None)
    product_image_url = models.TextField(default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product_name + " - qty ( " + str(self.product_quantity) + ") - cat (" + str(self.product_category.id) + ")"


class Orders(models.Model):
    order_user = models.ForeignKey(User, on_delete = models.SET_NULL, blank = True, null =True)
    order_summary = models.TextField()
    order_completed = models.BooleanField(default = False)
    order_comments = models.TextField()
    order_date = models.DateTimeField()
    order_completed_date = models.DateTimeField()

    def __str__(self):
        return self.order_user.username + str(self.order_date) + str(self.order_completed)

home_module/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from .models import Schemes, Category, Products
from django.http import Http404
from harbacore_home import UtitlityFunctions
from django.views import View, generic
import json

#imported python collections class
from collections import defaultdict

# Constants file
from . import Constants


####### Views ############

def index(request):
    if request.session.get('cart') is not None:
        print ("Cart in index page" ,request.session.get('cart'))
    else:
        print("cart is empty in index page")
    return HttpResponse("Hello, world. You're at the polls index.")

#get the user
def getCurrentUser(request):
    if request.user.is_authenticated:
        return request.user

class SchemesListView(View):
    scheme_id = 1

    def get(self, request,*args, **kwargs):
        if 'scheme_id' in self.kwargs and self.kwargs['scheme_id'] is not None:
            self.scheme_id = self.kwargs['scheme_id']

        # print ("kwargs ", kwargs)
        # print ("self.kwargs ", self.kwargs)
        # print ("in schemes")
        try :
            schemes_list = Schemes.objects.filter(is_active=True)
            selected_scheme = Schemes.objects.get(pk = self.scheme_id)
            tc = UtitlityFunctions.seperateStringOnBasisOfHtmlTags(
                                                            selected_scheme.terms_and_conditions,
                                                            ["<ul>","</ul>","<li>", "</li>"])
            terms_and_conditions = []
            for t_c in tc:
                if len(t_c)>0 and t_c!='':
                    terms_and_conditions.append(t_c)

            context = {
                'schemes_list' : schemes_list,
                'selected_scheme': selected_scheme,
                'terms_and_conditions': terms_and_conditions
            }
            # print("schemes list",schemes_list)
            # print("selected scheme ", selected_scheme)
            # print("terms ---> ",terms_and_conditions)
            return render(request=request, template_name='home_module/schemes_list.html', context=context)
        except Exception as e:
            print ("Exception as ", e)
            return render(request=request, template_name='home_module/page_404.html')


class ProductListView(View):
    #default category
    category_id = 2
    def get(self,request,*args, **kwargs):
        if 'category_id' in self.kwargs and self.kwargs['category_id'] is not None:
            self.category_id = self.kwargs['category_id']

        print ("kwargs ", kwargs)
        print ("self.kwargs ", self.kwargs)
        print("in products get")

        categories = Category.objects.filter(is_active=True)
        print ("categories ", categories)
        #can use _set.all() function too for a particular category in the html

        category_name = Category.objects.get(pk=self.category_id).category_name
        products = Products.objects.filter(product_category__id=self.category_id)

        processed_products_data =[]
        for product in products:
            temp = {}
            temp['product'] = product
            # print ("variants ", product.mapped_variant.all(), " name ", product.product_name)
            variant = defaultdict(list)
            for data in product.mapped_variant.all():
                variant[data.variant_name].append(data.variant_value)
            # print ("variant " ,variant)
            temp['variant'] = variant
            temp['final_price'] = product.product_mrp - 0.01*product.product_discount*product.product_mrp;
            processed_products_data.append(temp)

        #print ("processed ", processed_products_data)
        context = {
            'categories': categories,
            'data'  : processed_products_data,
            'category_name' : category_name
        }

        return render(request=request, template_name='home_module/category_list.html', context=context)

class AddToCartSessionView(View):

    def get(self, request, *args, **kwargs):
        print("AddToCartSessionView GET method")
        print ("session object ", request.session)
        print ("GET  params", request.GET)
        item_id = request.GET.get('item_id')
        item_quantity = request.GET.get('quantity')
        print ("item_id ->", item_id, "item_quanitty -> ", item_quantity)

        cart = request.session.get('cart', {})
        print("Cuurent cart before adding ", cart)

        if cart.get(item_id) is not None:
            messages.add_message(request=request, message="Item already present in Cart", level=messages.INFO)
        else:
            try:
                product = Products.objects.get(pk=int(item_id))
                updateData = {
                    item_id: int(item_quantity)
                }
                request.session = UtitlityFunctions.updateSessionObject(request, 'cart', updateData)
                request.session.modified = True
                print("After cart after adding ", request.session.get('cart'))
                # add message and display on page
                messages.add_message(request=request, message="Added to cart", level=messages.SUCCESS)

            except Products.DoesNotExist:
                messages.add_message(request=request, message="Product Does not exist", level=messages.SUCCESS)

        print ("Added to Cart")
        return redirect(reverse_lazy('home_module:cart'))


    def post(self, request, *args, **kwargs):
        print("Addtocart POST called")
        print("POST Cart object ", request.session.get('cart', {}))
        print ("session object ", request.session)
        print ("POST  params", request.POST)
        item_id = request.POST.get('item_id')
        item_quantity = request.POST.get('item_quantity')
        print("item_id ->", item_id, "item_quanitty -> ", item_quantity)
        print ("type of item_id ", type(item_id))

        try:
            product = Products.objects.get(pk=int(item_id))
            max_quantity = product.product_quantity
            print("max quantity ", max_quantity)
            if max_quantity < int(item_quantity):
                item_quantity = int(max_quantity)
                messages.add_message(request=request, message="Max quantity is " + str(max_quantity), level=messages.SUCCESS)
            update_data = {
                item_id: int(item_quantity)
            }
            request.session = UtitlityFunctions.updateSessionObject(request, 'cart', update_data)
            print("Cart dictionary after utilityFunction called ", request.session.get('cart', {}))
            return redirect(reverse_lazy('home_module:cart'))

        except Exception as e:
            print ("redirect to 404", e)
            redirect(render(request=request, template_name='home_module/page_404.html'))

class CartView(View):

    def get(self, request, *args, **kwargs):

        try:
            #getting cart session
            print("CartView")
            cart = request.session.get('cart', {})
            print ("Cart in Cart View" , cart)
            is_cart_empty = True
            total_amount = 0
            tax = 0
            data = []
            if len(cart) > 0:
                is_cart_empty = False
                for item_id, item_quantity in cart.items():
                    print ("type is ", type(item_id))
                    item_id = int(item_id)
                    item_quantity = int(item_quantity)
                    # print ("cart item_id "+str(item_id)+" item_quantity "+str(item_quantity))
                    product = get_object_or_404(Products, pk=item_id)
                    #adding item to data list to be finally shown to cart

                    temp = {}
                    temp['product_name'] = product.product_name
                    temp['product_quantity'] = item_quantity
                    temp['product_id'] = item_id
                    temp['product_final_price'] = product.product_mrp - 0.01*product.product_discount*product.product_mrp;
                    temp['product_mrp'] = product.product_mrp
                    temp['product_discount'] = product.product_discount
                    temp['final_quantity_amount'] = item_quantity * temp['product_final_price']
                    total_amount = total_amount + temp['final_quantity_amount']
                    data.append(temp)

            tax = (Constants.ELECTRICAL_PRODUCTS_TAX * total_amount) / 100
            payable_amount = tax + total_amount
            context = {
                'data': data,
                'is_cart_empty': is_cart_empty,
                'total_amount' : total_amount,
                'tax' : tax,
                'payable_amount' : payable_amount
            }
            print ("data ",data)
            return render(request=request, template_name='home_module/cart.html', context=context)

        except Exception as e:
            print ("Exception in cart ", e)
            return render(request=request, template_name='home_module/page_404.html')

class UpdateCartQuantity(View):

    def get(self, request, *args, **kwargs):
        print ("UpdateCartQuantityView Cart object ", request.session.get('cart',{}))
        request.session = UtitlityFunctions.updateSessionObject(request, 'cart', {kwargs['id']:kwargs['quantity']})
        print("Cart dictionary after utilityFunction called ", request.session.get('cart', {}))
        return HttpResponse("yes")

class TestListView(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):
        context = {
            'data' : self.kwargs['name']
        }
        return render(request=request, template_name="home_module/test.html", context=context)

class SubmitOrderView(LoginRequiredMixin,View):

    def get(self,request, *args, **kwargs):
        print ("inside SubmitOrder view")

home_module/templates/home_module/cart.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}
Cart | Harbacore
{% endblock title %}

<!--static block-->
{% block static %}
    <link rel="stylesheet" href="{% static 'home_module/css/cart.css' %}" >
{% endblock %}

{% block content %}

{% if is_cart_empty %}
    <h1>Sorry the cart is empty.</h1>
{% else %}

<div class="row">
    <div class="col-md-9">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <!--<th>MRP</th>-->
                    <!--<th>Discount</th>-->
                    <!--<th>Final Price per Piece</th>-->
                    <th>Quantity</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                    <tr>
                        <td>
                            <p>{{ item.product_name }} </p>
                            <p class="card-text">
                                ₹<b>{{item.product_final_price}}</b>
                                &nbsp
                                <del class="dull">{{item.product_mrp}}</del>
                                &nbsp
                                <span class="badge badge-info">{{item.product_discount}}% off</span>
                            </p>

                            <form method="post" action="{% url 'home_module:add_to_cart_session' %}">
                                {% csrf_token %}
                                <input type="hidden" value="{{item.product_id}}" name="item_id" />
                                <input type="hidden" value="-1" name="item_quantity" />
                                <!--<button onclick="test({{item.product_id}}, document.getElementById('product{{ item.product_id }}').value)">Update</button>-->
                                <!--<input type="submit" value="delete">-->
                                <button type="submit" class="btn btn-link dull" >
                                    <img class="glyph-size-delete" src="{% static 'images/si-glyph-delete.svg' %}" />
                                    Remove
                                </button>
                            </form>

                        </td>
                        <!--<td>{{ item.product_mrp }}</td>-->
                        <!--<td>{{ item.product_discount }}</td>-->
                        <!--<td>{{ item.product_final_price }}</td>-->
                        <td>
                            <form method="post" action="{% url 'home_module:add_to_cart_session' %}">
                                {% csrf_token %}
                                <input type="hidden" value="{{item.product_id}}" name="item_id" />
                                <input type="number" value="{{ item.product_quantity }}" name="item_quantity" />
                                <!--<button onclick="test({{item.product_id}}, document.getElementById('product{{ item.product_id }}').value)">Update</button>-->
                                <input type="submit" value="update">
                            </form>
                        </td>

                        <td>{{ item.final_quantity_amount }}</td>

                    </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>

    <!--payment summary-->
    <div class="col-md-3 payment-summary">
        <h6 style="margin-top:10px">Payment Summary</h6>
        <div class="row">
            <div class="col-md-5 view-size">Sub Total</div>
            <div class="col-md-7 arrange-right view-size">₹{{ total_amount }}</div>
        </div>

        <div class="row">
            <div class="col-md-5 view-size">Taxes</div>
            <div class="col-md-7 arrange-right view-size">₹{{ tax }}</div>
        </div>

        <div class="row">
            <div class="col-md-5 view-size">Transportation</div>
            <div class="col-md-7 arrange-right view-size frate-color">Free</div>
        </div>


        <br>
        <hr size="20">
        <div class="row">
            <div class="col-md-5 view-size"><b>Grand Total</b></div>
            <div class="col-md-7 arrange-right view-size"><b>₹{{ payable_amount }}</b></div>
        </div>

    </div>

</div>
{% endif %}

<div>
    <a href="{% url 'home_module:submit_order' %}" class="btn btn-info" role="button">Submit Order</a>
    <!--<a href="{% url 'home_module:submit_order' %}">Submit Order</a>-->
</div>

{% endblock %}

home_module/templates/home_module/category_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}

<!--addig the css of specific app-->
{% block static %}
<link rel="stylesheet" href="{% static 'home_module/css/home_module_base.css' %}" >
{% endblock %}

{% block title %}
{{ category_name }} | Harbacore
{% endblock title %}

{% block content %}

<div class="container-fluid">

    <div class="container">

        <div class="row">
            <!--schemes list-->
            <div class="col-sm-3 col-md-3 category">
                <ul class="list-group">
                    {% for category in categories %}
                    <li class="list-group-item ">
                        <a href="{% url 'home_module:product_list_page' category_id=category.pk %}"> {{ category.category_name }} </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <!--display current active item-->
            <div class="col-sm-9 col-md-9">
                <div class="row">
                    {% for item in data %}
                    <div class="col-md-4" style="margin-top:30px">
                        <div class="card" >
                            <img class="card-img-top product-img" src="{% static item.product.product_image_url %}" alt="{{ item.product.product_name}}" />
                            <h6 class="card-title title-from-image"><b>{{ item.product.product_name }}</b></h6>
                            <div class="card-body">
                                <p class="card-text">

                                            ₹<b>{{item.final_price}}</b>
                                            &nbsp
                                            <del class="dull">{{item.product.product_mrp}}</del>
                                            &nbsp
                                            <span class="badge badge-info">{{item.product.product_discount}}% off</span>

                                </p>
                                <a href="{% url 'home_module:add_to_cart_session' %}?item_id={{item.product.id}}&quantity=1" class="btn btn-primary">Add To Cart</a>

                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock content %}

home_module/templates/home_module/page_404.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Harbacore</title>
</head>
<body>
    <div class="error text-center">
        <!--<img src="images/temp_error.png" alt="" class="img-responsive">-->
        <p>Page 404</p>
    </div>
</body>
</html>

home_module/templates/home_module/schemes_list.html
{% extends "layout.html" %}

{% block title %}
    Schemes | Harbacore
{% endblock title %}

{% block content %}

    <div class="container-fluid">

        <div class="container">

            <div class="row">
                <!--schemes list-->
                <div class="col-sm-3 col-md-3 ">
                    <ul class="list-group">
                        {% for scheme_item in schemes_list %}
                            <li class="list-group-item ">
                                <a href="{% url 'home_module:schemes_detail_page' scheme_id=scheme_item.pk %}">{{ scheme_item }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <!--display current active item-->
                <div class="col-sm-9 col-md-9">
                    <h1>{{ selected_scheme.title }}</h1>
                    <p>
                        <div class="row">
                                <img class="img-fluid" src="{{ selected_scheme.image_url }}" />
                        </div>
                    </p>
                    <p>
                        <h4>Terms and Conditions:</h4>
                        <ul>
                            {% for t_c in terms_and_conditions %}
                                <li> {{ t_c }} </li>
                            {% endfor %}
                        </ul>
                    </p>
                </div>


            </div>

        </div>

    </div>

{% endblock content %}

home_module/templates/home_module/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {{ data }}

</body>
</html>