accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    # path('login/', views.LoginView.as_view(), name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUpView.as_view(), name='signup'),
    path('profile/', views.CreateProfile.as_view(), name='create_profile'),
    path('dealer/', views.DealerDetails.as_view(), name='dealer_details'),

]

harbacore_home/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'parent_module'

urlpatterns = [
    path('index/', views.Index.as_view(), name="index_page"),
    path('contact-form/', views.contact_form_view, name="contact_form"),
    path('home/', include('home_module.urls', namespace='home_module')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

home_module/urls.py
from django.urls import path

from . import views

app_name = 'home_module'

urlpatterns = [
    path('', views.index, name='index'),
    path('schemes/', views.SchemesListView.as_view(), name="schemes_default_page"),
    path('schemes/<int:scheme_id>', views.SchemesListView.as_view(), name="schemes_detail_page"),
    path('category/', views.ProductListView.as_view(), name="product_default_page"),
    path('category/<int:category_id>', views.ProductListView.as_view(), name="product_list_page"),
    path('test/<int:name>', views.TestListView.as_view(), name="test_list_page"),
    path('cartAdd/', views.AddToCartSessionView.as_view(), name='add_to_cart_session'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('updateCartQuantity/<str:id>/<int:quantity>', views.UpdateCartQuantity.as_view(), name="update_cart_quantity"),
    path('submitOrder/', views.SubmitOrderView.as_view(), name="submit_order")
]

templates/contact_form.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}
    Contact Form
{% endblock title %}

{% block content %}
    <div class="row">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_ul}}
            <input type="Submit">
        </form>
    </div>
{% endblock %}

templates/home.html
<html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--we are adding here a app specific css using dynamic binding-->

</head>

<body>
    <p>THis is fhome page</p>
    <p>Games today {{ games }}</p>

</body>

</html>

templates/index.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block static %}
    <script sr="https://raw.githubusercontent.com/frexy/svg-icon-webcomponent/master/build/iconwc.js"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
{% endblock %}

{% block content %}

    <!--Products-->
    <div class="row" style="margin-top:-35px">
        <div class="col-md-12">
            <h1 style="text-align:center">PRODUCTS</h1>
        </div>
    </div>


    <!--Module showing the direct link categories-->
    <div class="row category-div" style="margin-top:10px">
        <div class="col-md-2 col-sm-4 col-6 get-border">
            <a href="{% url 'home_module:schemes_default_page' %}">
            <figure>
                <a href="#"> <img src="{% static 'images/chandeliers.svg' %}" alt="Chandelier" /> </a>
                <figcaption >Chandeliers</figcaption>
            </figure>
            </a>
            <!--<img src="{% static 'images/chandeliers.svg' %}" alt="Chandelier">-->
        </div>

        <div class="col-md-2 col-sm-4 col-6 get-border">
            <figure class="figure">
                <a href=""><img src="{% static 'images/lights.svg' %}" alt="Lights"> </a>
                <figcaption>Lights</figcaption>
            </figure>
        </div>

        <div class="col-md-2 col-sm-4 col-6 get-border">
            <figure>
                <a href="{% url 'home_module:product_list_page' category_id=5 %}"> <img src="{% static 'images/fans.svg' %}" alt="fans"></a>
                <figcaption>Fans</figcaption>
            </figure>
        </div>

        <div class="col-md-2 col-sm-4 col-6 get-border">
            <figure>
                <a href=""> <img src="{% static 'images/wires.svg' %}" alt="wires"></a>
                <figcaption>Wires</figcaption>
            </figure>
        </div>

        <div class="col-md-2 col-sm-4 col-6 get-border">
            <figure>
                <a href=""> <img src="{% static 'images/consumer-goods.svg' %}" alt="wires"></a>
                <figcaption>Air Conditionar</figcaption>
            </figure>
        </div>

        <div class="col-md-2 col-sm-4 col-6 get-border">
            <figure>
                <a href=""> <img src="{% static 'images/heater.svg' %}" alt="wires"></a>
                <figcaption>Water Geyser</figcaption>
            </figure>
        </div>

    </div>


    <!--heading for carousal of schemes offers-->
    <div class="row" style="margin-top:50px">
        <div class="col-md-12">
        <h3 style="text-align:center">Sale !!!! Fan's lowest Prices, last date 25h December</h3>
        </div>
    </div>

    <!--Module showing the Carousal of schemes    -->
    <div class="row">
        <div id="demo" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
            </ul>

            <!-- The slideshow -->
            <div class="carousel-inner carousal-image-resize">
                <div class="carousel-item active ">
                    <img src="{% static 'images/gold-schemes.jpg' %}" class="rounded" alt="Los Angeles">
                </div>
                <div class="carousel-item ">
                    <img src="{% static 'images/gold-schemes2.jpg' %}" class="rounded" alt="Chicago">
                </div>
                <div class="carousel-item ">
                    <img src="{% static 'images/scheme-3.jpg' %}" class="rounded" alt="New York">
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>

        </div>
    </div>


    <!--upcoming products-->
    <div class="container-fluid text-center">

    <div class="row" style="margin-top:50px">
        <div class="col-md-12">
        <h3 style="text-align:center">UPCOMING PRODUCTS</h3>
        </div>
    </div>

    <br>
        <div class="row ">
            <div class="col-sm-4 " >
                <img class="glyph-size" src="{% static 'images/si-glyph-button-starburst.svg' %}"/>
                <br/><br/>
                <h4>Lithium Ion Battery</h4>
                <p>Future of Energy Storage </p>
            </div>
            <div class="col-sm-4 ">
                <img class="glyph-size" src="{% static 'images/si-glyph-leaf.svg' %}"/>
                <br/><br/>
                <h4>Solar Energy </h4>
                <p> For Better Environment </p>
            </div>

            <div class="col-sm-4">
                <img class="glyph-size" src="{% static 'images/si-glyph-road.svg' %}"/>
                <br/><br/>
                <h4>Battery Operated Vehical (BOV)</h4>
                <p>E-Bikes and E-Cars </p>
            </div>
        </div>
    </div>

    <!--Customers speeak-->
    <div class="container customer-speak">

        <div class="row" style="margin-top:50px">
            <div class="col-md-12">
            <h3 style="text-align:center">WHAT OUR CUSTOMER'S SAY</h3>
            </div>
        </div>

        <div id="carouselContent" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active text-center p-4">
                     <p>"Best of service and product , that's what all we need "<br><span>Trustee, PSIT Group</span></p>
                </div>
                <div class="carousel-item text-center p-4">
                    <p>"It's just not about business, building relations is also a key point"<br><span>Ankit Vishwakarma , A.Z Electrical</span></p>
                </div>

                <div class="carousel-item text-center p-4">
                     <p>"They actually know there stuff "<br><span>Vikas Gupta , MD, Akashdeep Group</span></p>
                </div>

            </div>
            <a class="carousel-control-prev" href="#carouselContent" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon " aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselContent" role="button" data-slide="next">
                <span class="carousel-control-next-icon " aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>


    <!-- Container (Contact Section) -->
    <div id="contact" class="container-fluid ">

        <div class="row" style="margin-top:50px; margin-bottom:20px">
            <div class="col-md-12">
            <h3 style="text-align:center">CONTACT</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-5">
                <div>
                <p><b>Contact us and we'll get back to you within 24 hours.</b></p>
                <p><img class="glyph-size-contact" src="{% static 'images/si-glyph-pin-map.svg' %}" /> &nbsp  Kanpur , India</p>
                <p><img class="glyph-size-contact" src="{% static 'images/si-glyph-smartphone.svg' %}"/> &nbsp +91 9415302372</p>
                <p><img class="glyph-size-contact" src="{% static 'images/si-glyph-mail.svg' %}" />  &nbsp harbacore@gmail.com</p>
                </div>
                <br>

                <!--links to different pages-->
                <div>

                </div>

            </div>

            <div class="col-sm-7 slideanim embed-responsive embed-responsive embed-responsive-4by3">
                <iframe class="embed-responsive-item"
                        src="https://docs.google.com/forms/d/e/1FAIpQLSfDCm6KDA_XoTTJOQ3ySfxVSybg0u5N5HHB2eV36X8SY1mTag/viewform?embedded=true"
                        width="600" height="50" frameborder="0" marginheight="0" marginwidth="0">Loading...
                </iframe>
            </div>

        </div>
    </div>


{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <!--&lt;!&ndash;js library to pass csrf token to all ajax request&ndash;&gt;-->
    <!--<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>-->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"  href="{% static 'css/layout.css' %}">

    <!--we are adding here a app specific css using dynamic binding-->
    {% block static %}
    {% endblock %}
</head>
<body>

    <!--navingation bar for all pages-->
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand logo-color" href="{% url 'index_page' %}" >HARBACORE</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home_module:schemes_default_page' %}">Schemes</a>
                    </li>
                    <li class="nav-item">
                    <li><a class="nav-link" href="{% url 'home_module:product_default_page' %}">Products</a>
                    </li>
                </ul>
                {% if user.username %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home_module:cart' %}">Cart</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Hi &nbsp<b>{{user.username}} </b>!
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                            <a class="dropdown-item" href="{% url 'accounts:create_profile' %}">Profile</a>
                            <a class="dropdown-item" href="{% url 'accounts:dealer_details' %}">Dealer</a>
                        </div>

                    </li>
                </ul>
                {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home_module:cart' %}">Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>


    </div>

    <div class="container" style="margin-top:80px">

        <!--for any messages present to show to user -->
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <!--block to add content dynamically-->
        {% block content %}
        {% endblock %}


    </div>

    <!--footer-->
    <footer class="container-fluid text-center footer-css">
        <a href="#myPage" title="To Top">
            <span class="glyphicon glyphicon-chevron-up"></span>
        </a>
        <p> Developed @ <a href="www.harbacore.com" title="Visit harbacore.com">www.harbacore.com</a></p>
    </footer>


    <script>

    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    </script>

</body>
</html>